---
driver:
  name: docker
  privileged: true
  use_sudo: false

platforms:
  - name: centos-7
    driver_config:
      require_chef_omnibus: "13.1.31"
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

  - name: centos-7-chef-12
    driver_config:
      require_chef_omnibus: "12.7.2"
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12.7.2 && rm install.sh

  - name: centos-68
    driver_config:
      require_chef_omnibus: "13.1.31"
      image: centos:6.8
      privileged: true
      provision_command:
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

  - name: centos-69
    driver_config:
      require_chef_omnibus: "13.1.31"
      image: centos:6.9
      privileged: true
      provision_command:
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

  - name: centos-69-chef-12
    driver_config:
      require_chef_omnibus: "12.7.2"
      image: centos:6.9
      privileged: true
      provision_command:
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12.7.2 && rm install.sh

  - name: debian-8-chef-12
    driver_config:
      require_chef_omnibus: "12.7.2"
      image: debian:8
      privileged: true
      provision_command:
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12.7.2 && rm install.sh

  - name: debian-8
    driver_config:
      require_chef_omnibus: "13.1.31"
      image: debian:8
      privileged: true
      provision_command:
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

provisioner:
  name: chef_solo

verifier:
  name: inspec

suites:
  - name: node
    run_list:
        - nodesource
        - nodesource::upgrade_npm
        - nodesource::yarn
  - name: node-8
    run_list:
        - nodesource
    attributes:
        node:
            version: '8.11.1-1'
            major_version: '8.x'
            checksum: 'nil'
  - name: node-yarn-version
    attributes:
        yarn:
            version: 0.27.5-1
    run_list:
        - nodesource
        - nodesource::upgrade_npm
        - nodesource::yarn
    verifier:
      inspec_tests:
        - tests/node.rb
        - tests/yarn.rb
