language: ruby
dist: trusty

matrix:
  include:
    - rvm: 2.3
      env: suite=node-centos-7
    - rvm: 2.3
      env: suite=node-yarn-version-centos-7
    - rvm: 2.3
      env: suite=node-centos-7-chef-12
    - rvm: 2.3
      env: suite=node-centos-69
    - rvm: 2.3
      env: suite=node-yarn-version-centos-69
    - rvm: 2.3
      env: suite=node-centos-69-chef-12
    - rvm: 2.3
      env: suite=node-centos-68
    - rvm: 2.3
      env: suite=node-debian-8-chef-12
    - rvm: 2.3
      env: suite=node-debian-8
    - rvm: 2.3
      env: suite=node-8-centos-7

sudo: required
services: docker

before_script:
  - make install
  - make bundle
  - make style

script: bundle exec kitchen test "$suite"
