FROM centos/systemd

            ENV container docker
            RUN yum clean all
            RUN yum install -y sudo openssh-server openssh-clients which curl
            RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
            RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ''

          RUN if ! getent passwd kitchen; then                 useradd -d /home/kitchen -m -s /bin/bash -p '*' kitchen;               fi
          RUN echo "kitchen ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          RUN echo "Defaults !requiretty" >> /etc/sudoers
          RUN mkdir -p /home/kitchen/.ssh
          RUN chown -R kitchen /home/kitchen/.ssh
          RUN chmod 0700 /home/kitchen/.ssh
          RUN touch /home/kitchen/.ssh/authorized_keys
          RUN chown kitchen /home/kitchen/.ssh/authorized_keys
          RUN chmod 0600 /home/kitchen/.ssh/authorized_keys

RUN sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
RUN systemctl enable sshd.service
RUN curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

RUN echo ssh-rsa\ AAAAB3NzaC1yc2EAAAADAQABAAABAQDCdMi7ZIhWoKZioibHLwFhx4a5ZRK5TpVZkfzQGW/qUnbZkfEVfOcg7ifPbuBeoK2AJ37ieFqOMqt1Ov8ERZh8F4Dp\+8OKV\+CTPzaAWGDawm9cvmiPNYbz6xXihPLO53BuuFI/mwCSKJDoCGWL\+yZPaoxxDBb8xIsS4LLw6wq9eejoos6Vybdtj2/nDVt5DZ/tjgA\+V3vXIhJqQYgtsdCH7nElwM2IHTRwdQSiHC0vyHj8nqfEeX2BVBAW9CArADu4KcopwCsWwtxULST7Kz0oSene\+21zy6vbtmZsfxdxGsWMZO1\+MGcWQ/PIpVu9uo4qQrsz8W5w14O4TA2DkYxH\ kitchen_docker_key >> /home/kitchen/.ssh/authorized_keys
